### ISSUE TITLE
katello-modified systems support ?

### ISSUE THREAD

**Issue by Obie38** [rocky-linux/rocky-tools#105]
Hi,

when I try to migrate with migrate2rocky script I get this issue :
Migration from katello-modified systems is not supported by migrate2rocky. 

The support of "katello-modified systems" will be enabled in the future ?
Is there a way to get by ?

Thanks to the team for all the work :)

**Comment by pajamian** [comment]
There are no current plans to support Katello in migrate2rocky, nor is there any way to reasonably do so due to the way that Katello modifies the system repositories it makes it impossible for migrate2rocky to properly migrate a system that has Katello installed.  I have heard of people managing to do migrations by uninstalling Katello, running migrate2rocky, and then re-installing Katello, but this is not supported and YMMV, it may work for you, or it may leave your system in an unbootable state.
