### ISSUE TITLE
New feature: Test mode?

### ISSUE THREAD

**Issue by bberndt** [rocky-linux/rocky-tools#108]
Is it possible to have a test mode of some sort?  I ask because I have one CentOS 8 machine left to migrate to Rocky. (the rest were standard VMs that I could snapshot)  Its a hardware machine, and used as a file server or sorts to store several TB of data backups; so I can't really back it up, for a possible failure.  It doesn't really have anything special installed, except for one thing:
A driver for the LSI/3Ware/Avaya/Broadcom HBA card. 
Serial Attached SCSI controller: Broadcom / LSI SAS2008 PCI-Express Fusion-MPT SAS-2 [Falcon] (rev 03)

if I recall, this was installed with information from
https://elrepoproject.blogspot.com/2019/08/rhel-80-and-support-for-removed-adapters.html
and the ELRepo repository. 

It appears to be booting from a software RAID 1, connected to the motherboard,  and then 2 HBA cards connect 16 drives in a software RAID 60

Any comments would be welcome. thanks.

**Comment by pajamian** [comment]
The unfortunate reality is that there is no way to accurately test the full scope of a migration before performing the migration.  migrate2rocky uses a number dnf and rpm commands, among other commands that must be performed in sequence in order to complete the migration.  Even a single dnf command can only partially be tested with the --assumeno option, and since the next command in line relies on the completion of the previous command it's impossible to know if a subsequent command will fail until the previous command is completed.

migrate2rocky does attempt to detect situations that will cause failure, though, via the use of a number of pre-migration checks and if any of these fail it will refuse to continue before it gets to the point where it will leave the system in an unstable state.  This is no guarantee but it does catch a number of common issues, and if you discover anything which it does not catch then I am always happy to hear about it so we can add a new test for it if possible.

In the event that a migration does fail it is usually possible to complete the migration by fixing the cause of the failure and then completing the remaining steps manually, often times just a dnf distro-sync is all that is needed at that point.  Always save the migrate2rocky.log file from a failed migration and share that with us so we can help you to complete the migration and get your system back up and running.  Also it pays to have a separate emergency boot image handy (disk, usb stick, etc).

Good luck with your migration!
