### ISSUE TITLE
Migrate after CentOS 8 EOL

### ISSUE THREAD

**Issue by aminvakil** [rocky-linux/rocky-tools#141]
I guess there should be problems after official mirrors remove CentOS 8 packages, as `migrate2rocky.sh` tries to execute `yum update -y` before doing anything.

What can we do to prevent this post-centos-removal-from-mirrors?

**Comment by pajamian** [comment]
This is certainly going to be an issue.  I had to this point put it in the "we'll cross this bridge when we get to it" basket, simply because the solution is going to involve redirecting centos requests to vault, but currently the repos aren't in vault.  It's kid of one of those issues where trying to solve it now is not going to be guaranteed to work and we won't really have any way to properly test the solution.

**Comment by aminvakil** [comment]
And there will be users who are using an out-dated `migrate2rocky.sh`...

**Comment by aminvakil** [comment]
There could be a soft warning which checks the latest `migrate2rocky.sh` from github and warns if it is not the latest one, this could help for other circumstances too IMHO.

This should definitely not be a barrier and force users to update as probably there are someones which execute this on local networks without internet access.

Not related to this issue but I could help creating a PR for this if you think it's useful.

**Comment by pajamian** [comment]
Sure.  I suppose it would first require us to actually set up version numbers for migrate2rocky, though.

**Comment by aminvakil** [comment]
> Sure. I suppose it would first require us to actually set up version numbers for migrate2rocky, though.

How about checking for differences between running `migrate2rocky` and latest from master?

**Comment by pajamian** [comment]
The only real way to do that would be some sort of checksum, and that would be spoiled by any kind of local modification to the script.

**Comment by PaulKGrimes** [comment]
I put this as a comment on a closed ticket, but maybe it's more relevant here:

I'm trying to migrate CentOS 8.1911 machines to Rocky Linux (they've fallen behind on updates because they're used for software and hardware development by multiple people in my lab).  Since CentOS 8 EoL, I have to edit my /etc/yum.repos.d/* files to comment out the mirrors line, and uncomment and change the baseurl to vault.centos.org to be able to update packages.  

To run the Rocky migration script, I first have to update dnf to >=4.2, which needs those changes above, but then the Rocky migration script fails, so I have to revert the /etc/yum.repos.d/* files to the original form which doesn't work in CentOS, and run the sed command mentioned in #153 

It'd be great if there was a way for the Rocky migration script to bring dnf, etc. up to date to allow migration of older versions of CentOS that someone might have lying around and which are now difficult to bring up to date now that CentOS 8 is EoL.  Or maybe just to deal with CentOS yum.repos.d/* files that have been modified to allow CentOS updates.

**Comment by pajamian** [comment]
It's more appropriate for a new issue.  Please don't use vault.centos.org for migrating, they have limited resources and we have mirrored vault so that our users can use that to migrate instead.
If you simply edit your CentOS-*.repo files, comment out the mirrorlist and uncomment change all the baseurl lines from:
`http://mirror.centos.org/$contentdir/$releasever/` ... to:
`https://dl.rockylinux.org/vault/centos/8.5.2111/`
...then the migration should work.

**Comment by pajamian** [comment]
Closing this issue as it's fixed with PR #154

**Comment by PaulKGrimes** [comment]
Thanks for the info.  I had already done the CentOS update to 8.2111 part before I found this and the related ticket.

It might be best handled with documentation rather than trying to make a script handle it.

**Comment by pajamian** [comment]
Right, a note in the known issues section of the README file would be appropriate.

**Comment by pajamian** [comment]
README updated with PR #155

**Comment by PaulKGrimes** [comment]
That looks great - I'll test it when I get to the next machine I have to migrate.
