### ISSUE TITLE
migrate2rocky.sh: Migration script not working when additional standard repos active

### ISSUE THREAD

**Issue by Millnert** [rocky-linux/rocky-tools#156]
Dear Rocky Linux rocky-tools maintainers,

first, a big thank you for the community service of Rocky Linux.

While attempting to execute migrate2rocky.sh on a pretty standardly installed host, patched to 8.5.2111 but not converted to Stream, migrate2rocky.sh (commit [9703480](https://github.com/rocky-linux/rocky-tools/commit/9703480c4dddc7e6268da0a326103d9a7de3dbd0) ) breaks.

I've isolated the fault to recent changes to `mirrorlist.centos.org` which no longer works with `$releasever=8`.
The problem is that `safednf`appears to handle the repositories AppStream, BaseOS, and PowerTools only, but a fairly vanilla install will have a fair amount additional repos active.  In my case, Extras and Plus are also active.

An example of a workaround could be to identify active repos with `^mirrorlist=http://mirrorlist.centos.org` line in them and add them to the ignore list. I don't know what the implications for the migration script of that is though.

I have O(100) hosts to convert now (finally forced to by the repository breakage) and volunteer to test any changes.

**Comment by pajamian** [comment]
Can you show the migrate2rocky.log file from the failed migration, please?

**Comment by pajamian** [comment]
So it turns out that I need to add plus to the list of repositories to migrate, and to the list of ones that need baseurl conversion from CentOS.  I'll do that and get back to you.

There is one other issue, though.  The Rocky Linux plus repository is much more sparse than the centosplus repository, so it may cause issues as well.  We'll see how it does once I've added it in, though.

**Comment by pajamian** [comment]
So there's a couple of issues here in creating a fix.  First off I can't just swap out the plus repo since it's completely different on each different distro.  Some distros don't even have a plus repo and those that do are not consistent with which packages are in it.

That said, I can change the baseurl to point to vault so you don't get this particular error.  Try the migrate2rocky script at https://raw.githubusercontent.com/pajamian/rocky-tools/plus/migrate2rocky/migrate2rocky.sh and see if it works.

Finally I fear that the above script may not work for you because the error message you're getting is for the "plus" repo, but in CentOS 8 the repo is named "centosplus", so somewhere along the line it seems like the repo got renamed for you.  At any rate, can you try this anyways and see if it works, and if not we can troubleshoot further.

**Comment by Millnert** [comment]
Hi!
Thank you for your response in the matter.

When I try to run the script, I get errors:

> [root@prod-office-nextcloud ~]# bash -r migrate2rocky.sh.1 
> migrate2rocky.sh.1: line 88: /var/log/migrate2rocky.log: restricted: cannot redirect output
> migrate2rocky.sh.1: line 117: 5: Bad file descriptor
> migrate2rocky.sh.1: line 118: 3: Bad file descriptor
> Usage: migrate2rocky.sh.1 [OPTIONS]
> 
> Options:
> -h Display this help
> -r Convert to rocky
> -V Verify switch
>    !! USE WITH CAUTION !!

I have worked around the issue by disabling the repos during the upgrade.

I understand the added complexity in the solution might simply exceed the benefits.  Perhaps a better approach is to update README.md simply stating clearly which repos are supported and that extra repos will have to be handled manually, in case someone else in the future is careful enough to read the instructions but not clever enough to figure out the workaround on their own. :-)

**Comment by pajamian** [comment]
> [root@prod-office-nextcloud ~]# bash -r migrate2rocky.sh.1

From the bash man page:
       -r        If the -r option is present, the shell becomes restricted (see RESTRICTED SHELL below).

You can't run migrate2rocky in a restricted shell.
Just `chmod 700 migrate2rocky.sh` and `./migrate2rocky.sh -r`

**Comment by Millnert** [comment]
Oh snap, my bad. I intended to apply '-r' as an argument to the script. Will retry tomorrow!

**Comment by Millnert** [comment]
@pajamian The combination of curating the repository list somewhat and your latest change works fine. I'm closing this issue now. Thanks for your help!
