### ISSUE TITLE
"Error: Unknown repo" during upgrade

### ISSUE THREAD

**Issue by nickosh** [rocky-linux/rocky-tools#159]
Hi. Have this problem during RHEL 8.5 to Rocky 8.5 migration:

> migrate2rocky - Begin logging at Fri Feb 11 08:53:30 2022.
> 
> 
> Removing dnf cache
> Preparing to migrate Red Hat Enterprise Linux 8.5 (Ootpa) to Rocky Linux 8.
> 
> Determining repository names for Red Hat Enterprise Linux 8.5 (Ootpa)......
> 
> Found the following repositories which map from Red Hat Enterprise Linux 8.5 (Ootpa) to Rocky Linux 8:
> 
> Getting system package names for Red Hat Enterprise Linux 8.5 (Ootpa)./migrate2rocky.sh: line 441: repoinfo_results_cache: bad array subscript
> Error: Unknown repo: ''
> 
> Failed to fetch info for repository .
> 
> An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

**Comment by nickosh** [comment]
Hmm, as I understand I need a configured repo and made 'dnf update' before script running. Maybe this is error origin.

**Comment by pajamian** [comment]
I will try to reproduce this today, it's been a while since I've tested migration from RHEL, so there could be an inherent problem there.
If I can't reproduce it I'll ask you for more info.

**Comment by pajamian** [comment]
The issue is likely that your RHEL subscription has expired.  If you're using the free "Red Hat Developer Subscription for Individuals" then see https://developers.redhat.com/articles/renew-your-red-hat-developer-program-subscription# for information on how to re-register.  If you have a paid subscription then you'll need to renew it in the access portal.  If you wish you can probably convert an expired paid subscription to a free developer subscription by first subscribing from the link at https://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available?source=sso#what_you_get then following the directions to re-register above.

**Comment by nickosh** [comment]
I do not updated RHEL before migration, thats was my problem. I restore my license and updated, then migration was successful. Thank you for help and sorry for bother!
