### ISSUE TITLE
migrate2rocky.sh error CAn;t get package what provides /etc/yum.repos.d/rhel8.repo

### ISSUE THREAD

**Issue by vipinbhidwaria** [rocky-linux/rocky-tools#168]
Please help as I am getting the following error.

[root@1111 rocky-tools]# ./migrate2rocky/migrate2rocky.sh -r
migrate2rocky - Begin logging at Tue 08 Mar 2022 01:21:09 PM IST.

Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Removing dnf cache
Preparing to migrate Red Hat Enterprise Linux 8.5 (Ootpa) to Rocky Linux 8.

Determining repository names for Red Hat Enterprise Linux 8.5 (Ootpa)......

Found the following repositories which map from Red Hat Enterprise Linux 8.5 (Ootpa) to Rocky Linux 8:
Red Hat Enterprise Linux 8.5 (Ootpa)  Rocky Linux 8
InstallMedia-AppStream                appstream
InstallMedia-BaseOS                   baseos

Getting system package names for Red Hat Enterprise Linux 8.5 (Ootpa)........Error: No Matches found

Can't get package that provides /etc/yum.repos.d/rhel8.repo.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

 A log of this installation can be found at /var/log/migrate2rocky.log

The following is log

migrate2rocky - Begin logging at Tue 08 Mar 2022 01:21:09 PM IST.

Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Removing dnf cache
Preparing to migrate Red Hat Enterprise Linux 8.5 (Ootpa) to Rocky Linux 8.

Determining repository names for Red Hat Enterprise Linux 8.5 (Ootpa)......

Found the following repositories which map from Red Hat Enterprise Linux 8.5 (Ootpa) to Rocky Linux 8:
Red Hat Enterprise Linux 8.5 (Ootpa)  Rocky Linux 8
InstallMedia-AppStream                appstream
InstallMedia-BaseOS                   baseos

Getting system package names for Red Hat Enterprise Linux 8.5 (Ootpa)........Error: No Matches found

Can't get package that provides /etc/yum.repos.d/rhel8.repo.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

**Comment by pajamian** [comment]
The issue is likely that your RHEL subscription has expired. If you're using the free "Red Hat Developer Subscription for Individuals" then see https://developers.redhat.com/articles/renew-your-red-hat-developer-program-subscription# for information on how to re-register. If you have a paid subscription then you'll need to renew it in the access portal. If you wish you can probably convert an expired paid subscription to a free developer subscription by first subscribing from the link at https://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available?source=sso#what_you_get then following the directions to re-register above.

**Comment by vipinbhidwaria** [comment]
I found a work around. First shifted to AlmaLinux and then to Rocky.

Alma Linux does not depend on subscription of RHEL for migration.
