### ISSUE TITLE
CentOs migration halts on missing CentOS SIG Storage key

### ISSUE THREAD

**Issue by setindustry** [rocky-linux/rocky-tools#171]
This is FYI in case others run into this. 
I'm on a clone of our HPC login node. We didn't have this installed, I don't see anything in the script that forces the install of it.

The migrate2rocky.sh stops during package verification because it couldn't find  /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Storage. I downloaded the GPG key from CentOS GPG keys website and created the file. I restarted the install and migration succeeded.

Excellent work, guys, can't thank you enough.
[migrate2rocky1.log](https://github.com/rocky-linux/rocky-tools/files/8533324/migrate2rocky1.log)
.

**Comment by setindustry** [comment]
As I stated, this was FYI. Closing.

**Comment by pajamian** [comment]
Thanks for the info.  I don't really consider this an issue because the command that it failed on was just an initial `dnf update` (which migrate2rocky purposefully runs first to try to make sure that the repos and packages are in a somewhat stable state).  The theory is that if it can't successfully perform a simple update then we will not proceed with the much more complicated migration.  The script worked as intended and stopped before any actual damage occurred to the system.

I'm glad you got it to work in the end.
