### ISSUE TITLE
Error migrating from CentOS 8.5 to Rocky via migrate2rocky script

### ISSUE THREAD

**Issue by GlenBleidd** [rocky-linux/rocky-tools#177]
I'm having issues regarding migrating our CentOS 8 Linux server to Rocky Linux via migrate2rocky. The output logs show the following:

```
migrate2rocky - Begin logging at Wed 15 Jun 2022 02:01:58 PM PST.

Error: Check discovered 1 problem(s)
OB2-NDMP-A.09.00-1.i386 has missing requires of OB2-CORE-IS = A.09.00-1

Errors found in dnf/rpm database.  Please correct before running migrate2rocky.

An error occurred while we were attempting to convert your system to Rocky Linux. Your system may be unstable. Script will now exit to prevent possible damage.

```
I already tried the migrate2rocky on a dummy server but when I try to execute it on a clone of our production I get the error above. Can anyone direct me on what to do? Tried googling but no results shows up.

Thanks!

**Comment by pajamian** [comment]
migrate2rocky is running `dnf check` and it's failing due to a missing dependency in your system.  If migrate2rocky were to proceed you would likely end up with a failed migration as a result.

This also looks to be a 3rd-party package (I don't recognize it) so the best course of action is to consult with the repository that provided the OB2 packages.  Two possible courses of action are:

1. Install the missing OB2-CORE-IS package.
2. Remove the OB2-NDMP package.

Peter

**Comment by GlenBleidd** [comment]
Hi Peter, thank you for the suggestion, unfortunately I have no idea too regarding that package but I will try to contact our other team if they know anything regarding the package.
