### ISSUE TITLE
How to convert Centos 8 Stream in disconnected environments without direct access to internet repos?

### ISSUE THREAD

**Issue by someconservator** [rocky-linux/rocky-tools#214]
We only have access to repositories provided by, for example, Foreman or Nexus.
Can we convert our Centos8Release systems to Rocky in this case of not having direct access to the repositories declared in the migration script? Maybe someone can tell how this can be done?

**Comment by pajamian** [comment]
You would have to make significant changes to migrate2rocky in order to do this:

* You need to change line 141 to point to the URL where the Rocky Linux 8 GPG key is stored.
* You need to change lines 150 and 151 to reflect your mirror's location of the baseos and appstream repos.
* And then you'd be left with a script that will likely still break because migrate2rocky gets the new .repo files for RockyLinux from the rocky-repos package which it initially installs.  You would have to somehow modify migrate2rocky so that it modifies the BaseURL locations in all of these .repo files before it runs the distro-sync.  This would require adding code to change the BaseURLs at around line 1075.

**Comment by someconservator** [comment]
yes, thank you, that’s what I understood and dealt with the problem by abandoning this script and doing the update manually.

**Comment by pajamian** [comment]
Glad to hear it worked out for you.  At some point I may get around to adding an option to do this with migrate2rocky, it's just a matter of getting the free cycles to do so.
