### ISSUE TITLE
Some packages break migrate2rocky

### ISSUE THREAD

**Issue by JoshuaPK** [rocky-linux/rocky-tools#46]
I don't know if this should be considered a "Defect" or "Feature Request", but can we have the script check for conditions that we know will make it fail?  For example, I had nodejs installed on my CentOS 8 laptop, from the nodejs repository.  When I ran migrate2rocky, the script abended because there was some conflict with npm.  After the abend the system was non-recoverable.  I attempted to simply run a 'dnf update' (thinking it would work since the Rocky base packages had been installed by this point) and it did update a few hundred packages, but the system was not bootable after that.

As more and more people use migrate2rocky, I'm sure they will report other conditions that break the script.  It would be nice if we had a list of "dangerous" packages and/or other conditions built-in to the script, so that it could check for these conditions and abort the migration.

**Comment by pajamian** [comment]
Absolutely, but we need to identify that stuff, then on a case-by-case basis see if there's either a way we can improve the script so that it works with those conditions or if we can't have it abort like you said.  Can you post the migrate2rocky.log file from the failed migration?
Also it's possible that dnf distro-sync may save it, possibly followed by re-installing grub.

**Comment by pajamian** [comment]
Closing due to lack of information.
